load(":consumer.bzl", "consumer")

consumer(
    name = "simple-list",
    src = "//basic/example_genrule:simple-list",
)

#consumer(
#    name = "list",
#    src = "//basic/example_genrule:list",
#)
