load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_binary(
    name = "hello",
    srcs = ["main.go"],
    deps = ["@com_github_sirupsen_logrus//:go_default_library"],
)
