load("@io_bazel_rules_go//go:def.bzl", "go_test")

go_test(
    name = "arrays",
    size = "small",
    srcs = ["array_test.go"],
)

go_test(
    name = "bench_test",
    srcs = ["array_test.go"],
)
